server:
  port: 8688
spring:
  rabbitmq:
    host: 192.168.26.128
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
