spring:
  application:
    name: alibaba-b
  cloud:
    nacos: # 配置nacos的地址
      username: nacos
      password: nacos
      server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: yh123
    url: jdbc:mysql://localhost:3306/lianxi?serverTimezone=UTC
    username: root
server:
  port: 8082

seata:
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: "" # 如果是默认的命名空间、不要写public
      group: DEFAULT_GROUP
      username: nacos
      password: nacos
      application: seata-server
  tx-service-group: seata-demo #? 事务组名称 必须和service.vgroupMapping的一致？
  service:
    vgroup-mapping: # 使用默认的组映射，相当于在一个组别下
      seata-demo: SH # 事务组与集群映射
    disable-global-transaction: false